stages:
  - stage: TestSuite
    displayName: Test suite
    jobs:
    - job: 'Linux'
      timeoutInMinutes: 0
      pool:
        vmImage: 'ubuntu-20.04'
      strategy:
        matrix:
          Python38_runtime_no_coverage:
            python.version: '3.8'
            script_name: dev/continuous-integration/run_test_suite.py
            standalone: false
            split_run: 1
          Python38_runtime_1:
            python.version: '3.8'
            script_name: dev/continuous-integration/run_test_suite.py
            standalone: false
            split_run: 1
            upload_coverage : true
          Python38_runtime_2:
            python.version: '3.8'
            script_name: dev/continuous-integration/run_test_suite.py
            standalone: false
            split_run: 2
            upload_coverage : true
          Python38_standalone:
            python.version: '3.8'
            script_name: dev/continuous-integration/run_test_suite.py
            standalone: true
            upload_coverage : true
      steps:
      - template: dev/continuous-integration/azure-steps.yml

  - stage: notify_coveralls
    displayName: Notify coveralls of test completion
    jobs:
      - job: coveralls
        pool: server
        steps:
          - task: InvokeRESTAPI@1
            inputs:
              serviceConnection: coveralls
              urlSuffix: repo_token=$(coveralls_repo_token)
              headers: |
                {
                "Content-Type": "application/json"
                }
              body: |
                {
                  "payload": {
                       "build_num": $(Build.BuildNumber),
                       "status": "done"
                  }
                }
