stages:
  - stage: TestSuite
    displayName: Test suite
    jobs:
    - job: 'OS_X'
      timeoutInMinutes: 0
      pool:
        vmImage: 'macOS-10.15'
      strategy:
        matrix:
          Python38_standalone:
            python.version: '3.8'
            script_name: examples/standalone/cuba_openmp.py
            standalone: true
      steps:
      - template: dev/continuous-integration/azure-steps.yml
